### PR TITLE
Fixes #7 add FailOnPromiseError configuration

### LINKED ISSUE #7: Add fail on promise error
There is no distinction between completed and completed exceptionally promise step. 
Can we add configuration to manage this 2 stages?

### PR DESCRIPTION
**Pull request by mxfo**

### CODE REVIEW

File: yupiik-batch-runtime/src/main/java/io/yupiik/batch/runtime/batch/builder/BatchChain.java [hunk 1]
```diff
@@ -104,7 +104,12 @@ default void run(final RunConfiguration configuration) { // todo: shouldn't we f
                     if (result.value() instanceof BatchPromise<?> promise) {
                         final var end = promise.end().toCompletableFuture();
                         promises.add(end);
-                        end.whenComplete((ok, ko) -> promises.remove(end));
+//                        end.whenComplete((ok, ko) -> promises.remove(end));
+                        end.whenComplete((ok, ko) -> {
+                            if (!end.isCompletedExceptionally() || configuration == null || !configuration.failOnPromiseError) {
```
Comment (rmannibucau) [inline yupiik-batch-runtime/src/main/java/io/yupiik/batch/runtime/batch/builder/BatchChain.java:109]: maybe `forceAwaitOnPromiseError` since we already fail if it does not finish early enough?

File: yupiik-batch-runtime/src/main/java/io/yupiik/batch/runtime/batch/builder/BatchChain.java [hunk 2]
```diff
@@ -249,7 +254,7 @@ private void await(final RunConfiguration configuration, final List<CompletableF
         }
         final var duration = configuration == null ? TimeUnit.MINUTES.toMillis(1) : configuration.maxBatchPromiseAwait;
         for (final var stage : new ArrayList<>(promises)) {
-            if (stage.isDone() || stage.isCompletedExceptionally()) {
+            if (stage.isDone() && (!configuration.failOnPromiseError || !stage.isCompletedExceptionally() )) {
```
Comment (rmannibucau) [inline yupiik-batch-runtime/src/main/java/io/yupiik/batch/runtime/batch/builder/BatchChain.java:257]: configuration can be null

File: yupiik-batch-runtime/src/test/java/io/yupiik/batch/runtime/batch/builder/BatchChainTest.java [hunk 3]
```diff
@@ -44,4 +46,25 @@ public String name() {
         };
         assertInstanceOf(TimeoutException.class, assertThrows(IllegalStateException.class, () -> infiniteStep.run(configuration)).getCause());
     }
+
+    @Test
+    void failOnPromiseError() {
```
Comment (rmannibucau) [inline yupiik-batch-runtime/src/test/java/io/yupiik/batch/runtime/batch/builder/BatchChainTest.java:51]: likely need another test ensuring it does not fail the other way around, the easier being to  use a two steps chain where first one will be returned completed (as you did here) so will be immediately removed (the falg being false) so the batch will NOT fail.
Then this test must set the toggle to true and ensure we fail in await probably.

File: yupiik-batch-runtime/src/main/java/io/yupiik/batch/runtime/batch/builder/BatchChain.java [hunk 4]
```diff
@@ -104,7 +104,12 @@ default void run(final RunConfiguration configuration) { // todo: shouldn't we f
                     if (result.value() instanceof BatchPromise<?> promise) {
                         final var end = promise.end().toCompletableFuture();
                         promises.add(end);
-                        end.whenComplete((ok, ko) -> promises.remove(end));
+//                        end.whenComplete((ok, ko) -> promises.remove(end));
```
Comment (rmannibucau) [inline yupiik-batch-runtime/src/main/java/io/yupiik/batch/runtime/batch/builder/BatchChain.java:107]: comment is not needed

**Review by rmannibucau — CHANGES_REQUESTED** [review]
Guess the toggle name is a bit ambiguous cause current behavior is not deterministic so a rename can be needed and a higher test coverage  sounds needed.

File: yupiik-batch-runtime/src/main/java/io/yupiik/batch/runtime/batch/builder/BatchChain.java (hunk 2 above)
Comment (mxfo) [reply yupiik-batch-runtime/src/main/java/io/yupiik/batch/runtime/batch/builder/BatchChain.java]: Use "true" value if configuration is null

File: yupiik-batch-runtime/src/test/java/io/yupiik/batch/runtime/batch/builder/BatchChainTest.java (hunk 3 above)
Comment (mxfo) [reply yupiik-batch-runtime/src/test/java/io/yupiik/batch/runtime/batch/builder/BatchChainTest.java]: adding success step in tests

File: yupiik-batch-runtime/src/main/java/io/yupiik/batch/runtime/batch/builder/BatchChain.java (hunk 2 above)
Comment (rmannibucau) [reply yupiik-batch-runtime/src/main/java/io/yupiik/batch/runtime/batch/builder/BatchChain.java]: hmm, where's the magic which makes "configuration" not null when it is null? :thinking:

File: yupiik-batch-runtime/src/main/java/io/yupiik/batch/runtime/batch/builder/BatchChain.java (hunk 4 above)
Comment (mxfo) [reply yupiik-batch-runtime/src/main/java/io/yupiik/batch/runtime/batch/builder/BatchChain.java]: removed
